name: ci-node
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js v18.16.1
        uses: actions/setup-node@v3
        with:
          node-version: v18.16.1

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run test
        run: npm run test
